#!/usr/bin/env ruby
$:.unshift(File.dirname(__FILE__))
#require 'g_dogist'
dir = File.dirname(__FILE__)
require dir+'/lib/g_dogist/gemfile_reader'
require dir+'/lib/g_dogist/searcher'

@reader   = GDogist::GemfileReader.new(ARGV[0])
gems      = @reader.gem_list
gems.each do|gem|
  p gem
  g_text_line = gem.split(/,/)
  text_element = g_text_line[0].gsub(/\"/,"")
                 .gsub(/\'/, "").gsub(/gem/, "").strip
  @searcher = GDogist::Searcher.new("\'" << text_element << "\'")
  @searcher.search
end

